# Generated by Django 4.0 on 2021-12-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='displays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=120)),
                ('intro1', models.TextField()),
                ('intro2', models.TextField()),
                ('detail1', models.TextField()),
                ('detail2', models.TextField()),
                ('detail3', models.TextField()),
                ('detail4', models.TextField()),
                ('extra', models.TextField()),
            ],
        ),
    ]
