# Generated by Django 4.0 on 2021-12-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='displays',
            new_name='Notes',
        ),
    ]
