# Generated by Django 4.0 on 2021-12-29 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_displays_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
