# Generated by Django 4.0 on 2021-12-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_rename_detail1_note_defn_remove_note_detail2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Term',
        ),
    ]
