# Generated by Django 4.0.1 on 2022-01-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=models.TextField(default='Enter your Blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Enter your title', max_length=120),
        ),
    ]
