# Generated by Django 4.0.1 on 2022-01-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_rename_user_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='user',
        ),
    ]
