# Generated by Django 4.0.1 on 2022-01-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_alter_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermSe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('defn', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Term',
            new_name='TermCs',
        ),
    ]
