# Generated by Django 4.0.1 on 2022-01-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_termse_rename_term_termcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termcs',
            name='defn',
            field=models.TextField(default='please enter the details'),
        ),
        migrations.AlterField(
            model_name='termcs',
            name='title',
            field=models.CharField(default='please enter the title', max_length=120),
        ),
        migrations.AlterField(
            model_name='termse',
            name='defn',
            field=models.TextField(default='please enter the details'),
        ),
        migrations.AlterField(
            model_name='termse',
            name='title',
            field=models.CharField(default='please enter the title', max_length=120),
        ),
    ]
