# Generated by Django 4.0.1 on 2022-01-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='user',
        ),
    ]
