# Generated by Django 4.0.1 on 2022-01-08 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_bugreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
