# Generated by Django 4.0.1 on 2022-01-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_alter_bugreport_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugreport',
            options={'ordering': ['-date']},
        ),
    ]
